[package]
name = "driveshaft"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam = { version = "^0.8.0" }
thiserror = { version = "^2.0.0" }
tokio = { version = "1.0", features = ["rt", "macros", "sync"] }
